#!/bin/sh
# Render docs/boards.md from boards.json. Run after editing boards.json:
#   ./scripts/gen-board-table.sh > docs/boards.md
set -eu
root="$(cd "$(dirname "$0")/.." && pwd)"
boards="${1:-${root}/boards.json}"
uboot="$(sed -n 's/^ARG U_BOOT_VERSION=\(.*\)/\1/p' "${root}/Dockerfile")"
total="$(jq '[.socs[].boards[]] | length' "${boards}")"

cat <<EOF
<!-- Generated by scripts/gen-board-table.sh from boards.json — do not edit by hand. -->
# Supported boards

${total} mainline-supported Rockchip ARM64 boards, built from U-Boot ${uboot}.

Each board has at least an SD / eMMC image; some also ship an SPI-flash image,
and the OP-TEE-capable SoCs ship an extra \`-optee\` variant. Filenames use the
U-Boot **defconfig** name:

- \`u-boot-<defconfig>.bin\` — write to SD card or eMMC (\`dd … seek=64\`).
- \`u-boot-<defconfig>-spi.bin\` — write to SPI flash (offset 0).
- \`u-boot-<defconfig>-optee.bin\` / \`-optee-spi.bin\` — same, with the OP-TEE secure world bundled.

The **FOSS** column marks boards whose entire boot chain is built from source (no
proprietary Rockchip blob): U-Boot's own TPL initialises DRAM and BL31 comes from
mainline Arm Trusted Firmware. Other boards embed Rockchip's prebuilt DDR and/or
BL31 blob from [rkbin](https://github.com/rockchip-linux/rkbin).

See [the README](../README.md) for download, flashing and verification steps.
EOF

jq -r '
  def bl31($s):
    if $s.bl31.kind == "rkbin" then "rkbin prebuilt BL31"
    elif ($s.bl31.version // "modern") == "legacy" then "TF-A v2.12.0"
    else "TF-A v2.15.0" end;
  .socs[] as $s
  | "",
    "## \($s.soc) — \($s.boards | length) boards",
    "",
    "BL31: \(bl31($s)) · DDR: \(if $s.ddr.kind == "uboot" then "U-Boot source" else "rkbin blob" end) · OP-TEE variant: \(if $s.optee_platform then "yes" else "no" end)",
    "",
    "| Board | SD / eMMC image | SPI image | FOSS |",
    "| --- | --- | --- | :---: |",
    ( $s.boards[]
      | "| \(.name) (`\(.defconfig)`) | `u-boot-\(.defconfig).bin` | "
        + (if .spi then "`u-boot-\(.defconfig)-spi.bin`" else "—" end)
        + " | " + (if .foss then "✅" else "—" end) + " |" )
' "${boards}"
